Predictify-org/predictify-contracts

contracts/predictify-hybrid/Cargo.toml
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/test.rs

This PR introduces comprehensive tests for the `resolve_market` function in the `PredictifyHybrid` contract to ensure its correctness and robustness according to the specified requirements.
This PR directly addresses the following validation tasks for `pub fn resolve_market(env: Env, market_id: Symbol) -> String`:
1.  **Ensure that the function cannot be called before the market end time:**
*   The test `test_resolve_market_before_end_time` verifies that calling `resolve_market` before the market's `end_time` results in the expected `Error::MarketClosed` panic.
2.  **Validate correct calculation of weighted results:**
*   The tests `test_resolve_market_oracle_wins_weighted` and `test_resolve_market_community_wins_weighted` specifically validate the 70/30 weighted resolution logic when the …

Feat: Implement Integration Tests for `resolve_market`

---

contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/test.rs

The `create_market` function (`pub fn create_market(env: Env, admin: Address, question: String, outcomes: Vec<String>, duration_days: u32) -> Symbol`) had several issues, including inconsistent storage keys, unreliable error handling with generic `panic!` calls, and missing edge case validations. The integration tests were also failing when cloning the repository due to authorization and storage mismatches. The task was to:
- Write integration tests to ensure market creation works correctly.
- Validate admin-only access.
- Verify fee deduction and correct storage of market data.
1. **Fixed Bug in `create_market` Function**:
- **Storage Key Mismatch**: The function used a hardcoded `Symbol::new(&env, "market")` for storing markets, causing test failures when tests expected a different key …

feat: create market test

---

contracts/predictify-hybrid/src/lib.rs

This PR introduces the `claim_winnings` function to the Predictify Hybrid contract, allowing users to claim their winnings from a resolved market. It also adds new fields to the `Market` struct to support secure and accurate claim tracking.
- **New Functionality:**  
- Added `claim_winnings(env, user, market_id)` to allow users to claim winnings if they voted for the winning outcome.
- Payouts are calculated based on the user’s stake relative to the total winning stakes, minus a 2% fee.
- Uses the token client to transfer winnings securely to the user.
- **State Management Enhancements:**  
- Added `stakes` (user-to-stake mapping), `claimed` (user-to-claim status), and `winning_outcome` (resolved outcome) fields to the `Market` struct.
- Users can only claim if they haven’t already, and …

Feat: Implement claim_winnings function and enhance market resolution logic

---

contracts/predictify-hybrid/src/lib.rs

This PR implements real integration with the Reflector oracle contract on Stellar, replacing the mock implementation with actual contract-to-contract calls for live price data.
- Added new contract types: `ReflectorAsset`, `ReflectorPriceData`, `ReflectorConfigData`
- Created `ReflectorOracleClient` for making real contract calls to Reflector
- Implemented `ReflectorOracle` struct with `OracleInterface` trait
- Added real contract calls to `lastprice()` and `twap()` functions
- Implemented fallback mechanism: if `lastprice()` fails, tries `twap()` with 1 record
- Updated `fetch_oracle_result` to support Reflector oracle provider
- Added proper error handling with `OracleUnavailable` error type
- **Contract Address**: `CALI2BYU2JE6WVRUFYTS6MSBNEHGJ35P4AVCZYF3B6QOE3QKOB2PLE6M`
- **Supported …

Feat: Implement Real Reflector Oracle Integration With Contract-To-Contract Calls

---

contracts/predictify-hybrid/src/lib.rs

This PR adds convenient helper functions to simplify market creation for specific oracle types, providing a cleaner API for developers to create markets with different oracle providers.
- Added `create_reflector_market()` function for Reflector oracle markets
- Added `create_pyth_market()` function for Pyth oracle markets  
- Added `create_reflector_asset_market()` function for asset-specific markets
- Each function automatically configures the appropriate `OracleConfig`
- Maintains consistent parameter validation and error handling
```rust
pub fn create_reflector_market(
env: Env,
admin: Address,
question: String,
outcomes: Vec<String>,
duration_days: u32,
asset_symbol: String,
threshold: i128,
comparison: String,
) -> Symbol
pub fn create_pyth_market(
env: Env,
admin: Address,
question: …
```

Feat: Add Helper Functions for Oracle-Specific Market Creation

---

README.md

📚 Create comprehensive README with detailed project description

---

contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/oracles.rs
contracts/predictify-hybrid/src/test.rs

refactor: Create dedicated oracles.rs module for centralized oracle management

---

contracts/predictify-hybrid/src/disputes.rs
contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/extensions.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/markets.rs
contracts/predictify-hybrid/src/oracles.rs
contracts/predictify-hybrid/src/test.rs
contracts/predictify-hybrid/src/types.rs
contracts/predictify-hybrid/src/voting.rs

Please select the type of change this PR introduces:
Closes #62
---
This PR introduces a comprehensive **market extension system** for the Predictify Hybrid contract. It allows market admins to extend the duration of a market under controlled and validated conditions, with fee handling, event logging, and extension history tracking. The following features are included:
- New contract functions for extending market duration, validating extension conditions, checking extension limits, emitting extension events, retrieving extension history, and handling extension fees.
- Extension approval and validation system, including admin checks, extension limits, and fee requirements.
- Storage and retrieval of extension history and statistics.
- Event emission for monitoring extension actions.
- …

Feat: Admin-Approved Duration Extensions with Limits, Fees, Events, and History Tracking

---

contracts/predictify-hybrid/src/config.rs
contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/extensions.rs
contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/test.rs
contracts/predictify-hybrid/src/voting.rs

This PR introduces a comprehensive configuration management system for the Predictify Hybrid contract, centralizing all constants, configuration structs, and environment-specific settings into a new `config.rs` module. This improves maintainability, flexibility, and clarity for all contract configuration.
- **New `config.rs` module**:
- Centralizes all contract constants (fees, voting, market, extension, resolution, oracle, storage).
- Provides configuration structs for each settings group (fees, voting, market, extension, resolution, oracle, network).
- Implements environment-specific configuration (development, testnet, mainnet).
- Adds configuration validation and helper utilities.
- Includes configuration testing utilities and documentation.
- **Refactored usage across modules**:
- …

Refactor: Centralized Configuration Management for Predictify Hybrid Contract

---

contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/test.rs
contracts/predictify-hybrid/src/validation.rs

Feat: Comprehensive Module Refactoring: Centralized Architecture for Predictify Hybrid Contract

---

contracts/predictify-hybrid/src/lib.rs

This PR introduces a comprehensive module organization and structure for the Predictify Hybrid contract. The codebase, previously monolithic and difficult to navigate, is now cleanly separated into logical modules, each with clear responsibilities and documentation.
closes #116 
- **Centralized Module Declarations:**  
All modules (`errors`, `types`, `oracles`, `markets`, `voting`, `disputes`, `resolution`, `fees`, `config`, `admin`, `events`, `validation`, `utils`, `extensions`) are now declared and imported in a single, well-documented section in `lib.rs`.
- **Improved Documentation:**  
Added high-level comments describing the purpose and relationships of each module, making the codebase easier to understand and maintain.
- **Incremental Refactoring:**  
Changes were made in small …

Refactor: Modularize Predictify Hybrid Contract for Maintainability and Clarity

---

contracts/predictify-hybrid/src/admin.rs
contracts/predictify-hybrid/src/config.rs
contracts/predictify-hybrid/src/disputes.rs
contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/events.rs
contracts/predictify-hybrid/src/extensions.rs
contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/markets.rs
contracts/predictify-hybrid/src/resolution.rs
contracts/predictify-hybrid/src/types.rs
contracts/predictify-hybrid/src/utils.rs
contracts/predictify-hybrid/src/validation.rs
contracts/predictify-hybrid/src/voting.rs

This PR addresses and completely eliminates all 82 compiler warnings in the Predictify Hybrid contract codebase, achieving a clean build with zero warnings and zero errors.
- **Unused Variables**: Prefixed 82 unused parameters with underscores (`_`) across all modules
- **Unused Imports**: Removed unused import statements
- **Type Mismatches**: Fixed function signature inconsistencies
- `lib.rs` - Core contract interface and function signatures
- `types.rs` - Data structure definitions and validation functions
- `voting.rs` - Voting system implementation
- `disputes.rs` - Dispute resolution system
- `resolution.rs` - Market resolution logic
- `fees.rs` - Fee calculation and management
- `config.rs` - Configuration management
- `validation.rs` - Input validation utilities
- `utils.rs` - …

Eliminate All Compiler Warnings in Predictify Hybrid Contract

---

ATTACK-VECTORS.md
AUDIT_CHECKLIST.md
INCIDENT_RESPONSE.md
SECURITY_BEST_PRACTICES.md
SECURITY_CONSIDERATIONS.md
SECURITY_TESTING_GUIDE.md

Please select the type of change this PR introduces:
Closes #(issue number)
Fixes #(issue number)
Related to #83 
---
- Added security considerations and threat models
- Attack vector analysis with mitigations included
- Documentation of best practices and audit procedures
- Better compatibility with secure development and readiness
- Incident response, monitoring, and update guides included
---
Please check all that apply:
---
```bash
cargo test
```
1. 
2. 
3. 
---
**Breaking Changes:**
- 
- 
**Migration Guide:**
---
- **Gas Usage**: 
- **Storage Impact**: 
- **Computational Complexity**: 
---
- **Network**: Testnet/Mainnet
- **Contract Address**: 
- **Migration Required**: Yes/No
- **Special Instructions**: 
---
- **End Users**: 
- **Developers**: 
- **Admins**: 
- **Revenue**: 
- …

docs(security) : add comprehensive security documentation

---

contracts/hello-world/src/lib.rs
contracts/predictify-hybrid/src/admin.rs
contracts/predictify-hybrid/src/config.rs
contracts/predictify-hybrid/src/disputes.rs
contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/events.rs
contracts/predictify-hybrid/src/extensions.rs
contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/integration_test.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/markets.rs
contracts/predictify-hybrid/src/oracles.rs
contracts/predictify-hybrid/src/resolution.rs
contracts/predictify-hybrid/src/test.rs
contracts/predictify-hybrid/src/types.rs
contracts/predictify-hybrid/src/utils.rs
contracts/predictify-hybrid/src/validation.rs
contracts/predictify-hybrid/src/voting.rs

This PR addresses GitHub issue #141 which reported 51 failing test cases due to fee management, event logging, utility functions, and integration issues affecting the contract's operational and monitoring capabilities.
- ✅ **Fixed fee calculation and collection logic**
- ✅ **Resolved event emission and logging issues**
- ✅ **Ensured utility functions work correctly**
- ✅ **Achieved 100% pass rate for operational functionality**
The failures were primarily caused by:
- HostError: Error(Contract, #1) in fee operations
- Event emission failures
- Utility function integration issues
- Test setup problems for complex scenarios
- `test_fee_analytics_calculation` ✅
- `test_fee_analytics_fee_efficiency` ✅
- `test_fee_analytics_market_fee_stats` ✅
- `test_fee_calculator_dynamic_fee` ✅
- …

Fix Fees, Events, Utilities & Integration Tests (Part 3/3) - Resolve All Test Failures #141

---

contracts/predictify-hybrid/src/errors.rs

🚨 Create Detailed Error System with Categorization and Recovery Mechanisms #72

---

contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/lib.rs

This MR implements comprehensive fee collection validation and safety mechanisms to enhance the security, transparency, and reliability of fee operations in the Predictify Hybrid contract.
- **`FeeCollectionStatus`**: Comprehensive status information with eligibility checks, warnings, and recommendations
- **`FeeDistribution`**: Fee distribution tracking across multiple recipients with audit trails
- **`FeeRefund`**: Complete refund record system for error handling and user protection
- **`FeeSafetyValidation`**: Safety validation results with risk scoring and recommendations
1. **`validate_fee_collection()`** - Comprehensive fee validation with safety checks
2. **`track_fee_distribution()`** - Fee distribution tracking and verification
3. **`verify_fee_collection_safety()`** - Safety …

feat: Implement Comprehensive Fee Collection Validation and Safety Mechanisms

---

contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/lib.rs

This PR implements a comprehensive multi-party fee distribution system that moves beyond the current single admin address model to support configurable fee distribution among multiple parties with governance capabilities.
- **`distribute_fees_to_parties()`** - Distributes collected fees to multiple recipient addresses based on configurable percentages
- **`validate_fee_dist_percentages()`** - Validates that distribution percentages sum to 100%
- **`validate_distribution_totals()`** - Ensures distribution amounts match collected fees
- **`get_fee_distribution_config()`** - Retrieves current fee distribution configuration
- **`update_fee_distribution_config()`** - Allows admins to update distribution settings
- **`FeeDistributionConfig`** - New struct managing recipient addresses, …

feat: Implement Multi-Party Fee Distribution System with Governance

---

contracts/predictify-hybrid/src/markets.rs
contracts/predictify-hybrid/src/validation.rs
contracts/predictify-hybrid/src/validation_tests.rs

feat: Implement comprehensive MarketParameterValidator for robust market creation

---

contracts/predictify-hybrid/src/validation.rs
contracts/predictify-hybrid/src/validation_tests.rs

feat: Implement OracleConfigValidator for robust oracle configuration validation

---

contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/markets.rs
contracts/predictify-hybrid/src/oracles.rs
contracts/predictify-hybrid/src/reentrancy_guard.rs
contracts/predictify-hybrid/src/resolution.rs
contracts/predictify-hybrid/src/voting.rs

- Closes #52
---
- Implements a global, cross-function reentrancy guard to protect against reentrancy during external calls.
- Centralizes token transfer and oracle invocation protections.
- Ensures state is updated only after successful external calls and provides a helper for state restoration on failure.
- Prior to this PR, the contract had no reentrancy guard, leaving it vulnerable to cross-function reentrancy attacks. Attackers could reenter other public functions while the contract was mid external call (token transfer, oracle invoke), potentially observing or mutating inconsistent state.
- Added unit tests for the guard lifecycle and blocking behavior in `reentrancy_guard.rs` using `env.register_contract` + `env.as_contract`.
- Ensured all external call sites are covered and that …

feat: add reentrancy protection for external calls and token transfers

---

contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/versioning.rs

This MR implements a comprehensive versioning system for the Predictify contract that enables safe contract upgrades, data migration between versions, and version compatibility validation.
- No versioning system existed to track contract versions
- No mechanism for data migration between contract versions
- No version compatibility validation
- No upgrade or rollback procedures
- No version history tracking
Implemented a complete versioning system with the following components:
- **Version Structure**: Tracks major, minor, patch versions with compatibility information
- **Version History**: Maintains complete version history with timestamps and migration records
- **Version Manager**: Central manager for all versioning operations
- **Migration System**: Handles data migration between …

feat: implement comprehensive contract versioning system with data migration support

---

contracts/predictify-hybrid/src/admin.rs
contracts/predictify-hybrid/src/batch_operations.rs
contracts/predictify-hybrid/src/batch_operations_tests.rs
contracts/predictify-hybrid/src/circuit_breaker.rs
contracts/predictify-hybrid/src/circuit_breaker_tests.rs
contracts/predictify-hybrid/src/disputes.rs
contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/events.rs
contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/markets.rs
contracts/predictify-hybrid/src/oracles.rs
contracts/predictify-hybrid/src/resolution.rs
contracts/predictify-hybrid/src/storage.rs
contracts/predictify-hybrid/src/test.rs
contracts/predictify-hybrid/src/voting.rs

Implement Error Recovery Mechanisms and Resilience Patterns #100

---

contracts/predictify-hybrid/src/events.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/upgrade_manager.rs
contracts/predictify-hybrid/src/upgrade_manager_tests.rs
contracts/predictify-hybrid/src/versioning.rs

Adds comprehensive upgrade functionality with proposal workflows, version compatibility validation, rollback support, and complete audit trails.
Please select the type of change this PR introduces:
- Closes #90 
---
This PR implements a comprehensive upgrade management system for the Predictify Hybrid Soroban smart contract. It adds the ability to safely upgrade contract WASM code while maintaining state, with built-in safeguards including:
- **Proposal-based workflow**: Upgrades must be proposed, validated, and approved before execution
- **Version compatibility checking**: Automatic detection of breaking changes using semantic versioning
- **Rollback capability**: Stores previous WASM hashes to enable quick rollback if issues occur
- **Audit trail**: Complete history of all upgrades …

Feat: implement Upgradeable Contract pattern for `Predictify`

---

contracts/predictify-hybrid/src/admin.rs
contracts/predictify-hybrid/src/batch_operations.rs
contracts/predictify-hybrid/src/batch_operations_tests.rs
contracts/predictify-hybrid/src/circuit_breaker.rs
contracts/predictify-hybrid/src/circuit_breaker_tests.rs
contracts/predictify-hybrid/src/disputes.rs
contracts/predictify-hybrid/src/edge_cases.rs
contracts/predictify-hybrid/src/errors.rs
contracts/predictify-hybrid/src/events.rs
contracts/predictify-hybrid/src/fees.rs
contracts/predictify-hybrid/src/governance.rs
contracts/predictify-hybrid/src/graceful_degradation.rs
contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/recovery.rs
contracts/predictify-hybrid/src/recovery_tests.rs
contracts/predictify-hybrid/src/resolution.rs
contracts/predictify-hybrid/src/storage.rs
contracts/predictify-hybrid/src/test.rs
contracts/predictify-hybrid/src/upgrade_manager.rs
contracts/predictify-hybrid/src/upgrade_manager_tests.rs
contracts/predictify-hybrid/src/versioning.rs

Closes #86
---
Implements a comprehensive event emission system for the Predictify prediction market contract. Adds complete event tracking for all critical contract operations including market creation, voting, oracle results, disputes, fee collection, state changes, winnings claims, and error events.
The contract previously lacked a systematic event emission infrastructure. This prevented:
- Real-time monitoring of contract activities
- Audit trail creation for compliance
- External integrations via event-driven architecture
- User activity tracking and analytics
- Transparent state change tracking
```bash
cargo test
cargo build
cargo fmt --all
cargo clippy
```
---
---
```bash
cargo test
test result: ok. 202 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 46.51s
``` …

feat: Implement comprehensive event emission system

---

contracts/predictify-hybrid/src/lib.rs
contracts/predictify-hybrid/src/market_analytics.rs
contracts/predictify-hybrid/src/market_id_generator.rs
contracts/predictify-hybrid/src/performance_benchmarks.rs

Please select the type of change this PR introduces:
Closes #54
---
This PR implements a collision-resistant market ID generation system that replaces the simple counter-based approach with a robust, multi-factor unique ID generator. The new system ensures guaranteed uniqueness across all admins and time periods using per-admin counters and cryptographic hashing.
**Key Changes:**
- Introduced `MarketIdGenerator` module with comprehensive ID generation logic
- Implemented per-admin counter tracking to prevent cross-admin collisions
- Added SHA256-based hash generation for deterministic unique IDs
- Created market ID registry system with pagination support
- Integrated collision detection with automatic retry mechanism
- Added format validation and legacy format support
The previous market …

feat: Add Collision-Resistant Market ID Generation System
